<a href="https://colab.research.google.com/github/DipyamanGoswami/Mathematics_Problem_Classification/blob/main/Bytelearn_math_problem_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
np.random.seed(2021)

In [ ]:
train_data= pd.read_csv("train.csv")
train_data

problem  category
0    At a ring toss game at a carnival, Marco throw...        19
1    What is `471 ÷ 100`? Interactive: Students fol...        22
2    Follow the directions below to create an equiv...        20
3    Solve the following system by substitution:\n`...        14
4    Solve the following system by substitution:\n`...        14
..                                                 ...       ...
245  Write an expression to match the phrase:"`9` p...         1
246  Identify the terms, coefficients, variables, a...         0
247  Solve the following system by elimination:\n`-...        12
248  Write an expression to match the phrase:"`8` t...         1
249  The first time Sue made enchiladas, she used `...         7

[250 rows x 2 columns]

In [ ]:
train_data.info

<bound method DataFrame.info of                                                problem  category
0    At a ring toss game at a carnival, Marco throw...        19
1    What is `471 ÷ 100`? Interactive: Students fol...        22
2    Follow the directions below to create an equiv...        20
3    Solve the following system by substitution:\n`...        14
4    Solve the following system by substitution:\n`...        14
..                                                 ...       ...
245  Write an expression to match the phrase:"`9` p...         1
246  Identify the terms, coefficients, variables, a...         0
247  Solve the following system by elimination:\n`-...        12
248  Write an expression to match the phrase:"`8` t...         1
249  The first time Sue made enchiladas, she used `...         7

[250 rows x 2 columns]>

In [ ]:
train_data['category'].value_counts

<bound method IndexOpsMixin.value_counts of 0      19
1      22
2      20
3      14
4      14
       ..
245     1
246     0
247    12
248     1
249     7
Name: category, Length: 250, dtype: int64>

In [ ]:
pip install -U sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 3.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 59.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 72.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.8/236.8 kB 26.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 88.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 72.4 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125926 sha256=859709845eeaeec8f2eeb1429ea5ba2c51283ac5d85c0f9832ddd8ca6675b9f5
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence-transformers


In [ ]:
from sentence_transformers import SentenceTransformer
model= SentenceTransformer('all-mpnet-base-v2')

In [ ]:
import spacy
nlp= spacy.load("en_core_web_sm")

In [ ]:
stopwords= nlp.Defaults.stop_words
stopwords

{"'d",
 "'ll",
 "'m",
 "'re",
 "'s",
 "'ve",
 'a',
 'about',
 'above',
 'across',
 'after',
 'afterwards',
 'again',
 'against',
 'all',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'amount',
 'an',
 'and',
 'another',
 'any',
 'anyhow',
 'anyone',
 'anything',
 'anyway',
 'anywhere',
 'are',
 'around',
 'as',
 'at',
 'back',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'behind',
 'being',
 'below',
 'beside',
 'besides',
 'between',
 'beyond',
 'both',
 'bottom',
 'but',
 'by',
 'ca',
 'call',
 'can',
 'cannot',
 'could',
 'did',
 'do',
 'does',
 'doing',
 'done',
 'down',
 'due',
 'during',
 'each',
 'eight',
 'either',
 'eleven',
 'else',
 'elsewhere',
 'empty',
 'enough',
 'even',
 'ever',
 'every',
 'everyone',
 'everything',
 'everywhere',
 'except',
 'few',
 'fifteen',
 'fifty',
 'first',
 'five',
 'for',
 'former',
 'formerly',
 'forty',
 'four',
 'from',
 'fron

In [ ]:
import string
punc= string.punctuation
list(punc)

['!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~']

In [ ]:
def tokenize(sentence):
  doc= nlp(sentence)

  # lemmatizing each token to convert it into base form and then converting it to lower case and removing any whitespaces
  tokens= [w.lemma_.lower().strip() for w in doc]

  #print(tokens)

  # removing any stop words and punctuations present in the sentences
  new_tokens= [x for x in tokens if x not in stopwords and x not in punc]

  sentences= " ".join(new_tokens)
  return sentences

In [ ]:
tokenize("My name is Dipyaman and I love programming") # A testcase

'dipyaman love programming'

In [ ]:
tokenized_data= train_data['problem'].apply(tokenize)
#tokenized_data

In [ ]:
embeddings= tokenized_data.apply(model.encode)
#embeddings

In [ ]:
train_data['tokenized_data']= tokenized_data
train_data['embeddings']= embeddings
#train_data

In [ ]:
x= train_data['embeddings'].to_list()
y= train_data['category'].to_list()

In [ ]:
test_data= pd.read_csv("test.csv")
#test_data

In [ ]:
import re
regex= re.compile(r'<[^>]+>')

def remove_tags(sentence):
  return regex.sub('', sentence)


In [ ]:
processed_test_data= test_data['problem'].apply(remove_tags)
#processed_test_data

In [ ]:
tokenized_test_data= processed_test_data.apply(tokenize)
#tokenized_test_data
embedded_test_data= tokenized_test_data.apply(model.encode)
#embedded_test_data

In [ ]:
test_data['processed_test_data']= processed_test_data
test_data['tokenized_test_data']= tokenized_test_data
test_data['embedded_test_data']= embedded_test_data
#test_data

In [ ]:
x_to_pred= test_data['embedded_test_data'].to_list()
#x_test

In [ ]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

mdl= KNeighborsClassifier()

x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=8)

mdl.fit(x_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred= mdl.predict(x_test)
y_pred

array([ 3,  7, 23,  3, 14,  6, 13,  9, 11, 20,  2,  4, 11, 13,  7,  3, 16,
       17,  7, 17, 14, 14,  9,  1,  0, 13,  9, 13,  5, 23,  0, 12,  7, 17,
        5, 12, 11, 14, 17, 24,  7, 16, 24,  2, 10, 15, 11,  3, 22,  2])

In [ ]:
accuracy= accuracy_score(y_pred, y_test)
accuracy

0.84

In [ ]:
Y_test=np.array(y_test)
Y_test.reshape(-1)

array([ 3, 21, 23,  3, 14,  8, 13,  9, 11, 20,  2,  4, 11, 13, 10,  3, 16,
       19,  7, 17, 14, 14,  9,  1,  0, 13,  7, 13,  5, 23,  0, 12, 18, 17,
        5, 12, 11, 14, 17, 24,  7, 16, 24,  3, 10, 15, 11,  2, 22,  2])

In [ ]:
category_predicted= mdl.predict(x_to_pred)
category_predicted

array([17,  7,  7,  9,  4, 23,  2,  4, 24,  8,  4,  4,  3,  7, 11, 23,  2,
        2,  4, 16, 16, 22,  6, 17,  7,  7,  7, 12, 14,  7, 14,  7,  7, 22,
       11,  7,  7,  9, 19,  1, 17, 17, 15,  3, 12, 20,  0,  2,  0,  7, 23,
       11, 24, 24, 15, 17, 20,  1, 13,  7,  7,  7,  9, 14,  1,  6, 14, 17,
        9,  5,  4, 22,  7, 13,  7,  5,  0, 14,  1, 13,  7, 15, 16, 24, 11,
       15,  6, 19,  7, 12,  7, 22, 24,  3, 14, 11, 20,  4, 23, 15,  6, 17,
       14,  5,  3, 20,  5,  4,  3, 12,  0,  0,  7,  7, 12, 21, 23,  7,  7,
        7,  8,  6, 20, 22,  2])

In [ ]:
test_data['category']= category_predicted
test_data

problem  category  \
0    <p>For graduating from middle school,  Wayne r...        17   
1    <p>Mrs. O'Hare bought `18` packs of pencils to...         7   
2    <p>Annalise bought `p` pens last week and `15`...         7   
3    <p>Felicia is decorating cupcakes for a party....         9   
4    <p>Write an expression to match the phrase:</p...         4   
..                                                 ...       ...   
120  <p>Veronica has `d` more dresses than Larisa d...         8   
121  <p>Write an equation to match the phrase:</p><...         6   
122  <p>Follow the directions below to create an eq...        20   
123  <p>What is `7.5 ÷ 10`?</p><selectivedisplay da...        22   
124  <p>Write an expression to match the phrase:<br...         2   

                                   processed_test_data  \
0    For graduating from middle school,  Wayne rece...   
1    Mrs. O'Hare bought `18` packs of pencils to gi...   
2    Annalise bought `p` pens last week and `15` ne...   
3    Felicia is decorating cupcakes for a party. Th...   
4    Write an expression to match the phrase:"`n` s...   
..                                                 ...   
120  Veronica has `d` more dresses than Larisa does...   
121  Write an equation to match the phrase:"the sum...   
122  Follow the directions below to create an equiv...   
123  What is `7.5 ÷ 10`? Interactive: Students foll...   
124  Write an expression to match the phrase:\n''`3...   

                                   tokenized_test_data  \
0    graduate middle school wayne receive 100 gift ...   
1    mrs. o'hare buy 18 pack pencil student classro...   
2    annalise buy p pen week 15 new pen week pen an...   
3    felicia decorate cupcake party 60 cupcake far ...   
4    write expression match phrase:"`n square reduc...   
..                                                 ...   
120  veronica d dress larisa larisa 3 dress dress v...   
121        write equation match phrase:"the sum m 7 12   
122  follow direction create equivalent fraction 1/...   
123  7.5 ÷ 10 interactive student follow step creat...   
124  write expression match phrase '' 3 subtract re...   

                                    embedded_test_data  
0    [0.008946019, 0.0118158385, -0.0022562465, 0.0...  
1    [-0.009747344, 0.019809125, 0.016297108, 0.022...  
2    [-0.004741377, 0.04046971, 0.01851571, -0.0099...  
3    [-0.009917497, 0.007995306, -0.0072740535, 0.0...  
4    [-0.0024829446, 0.037657674, -0.009346366, 0.0...  
..                                                 ...  
120  [0.00040075305, -0.0170574, -0.020821193, 0.04...  
121  [0.010018564, -0.003690077, 0.009549416, 0.018...  
122  [0.0019259584, -0.067262, -0.044282716, -0.009...  
123  [-0.03231625, -0.084767506, -0.020900482, -0.0...  
124  [0.029755639, -0.054434195, -0.0149794845, 0.0...  

[125 rows x 5 columns]

In [ ]:
final= pd.DataFrame({'problem':test_data['problem'], 'category':test_data['category']})
final

problem  category
0    <p>For graduating from middle school,  Wayne r...        17
1    <p>Mrs. O'Hare bought `18` packs of pencils to...         7
2    <p>Annalise bought `p` pens last week and `15`...         7
3    <p>Felicia is decorating cupcakes for a party....         9
4    <p>Write an expression to match the phrase:</p...         4
..                                                 ...       ...
120  <p>Veronica has `d` more dresses than Larisa d...         8
121  <p>Write an equation to match the phrase:</p><...         6
122  <p>Follow the directions below to create an eq...        20
123  <p>What is `7.5 ÷ 10`?</p><selectivedisplay da...        22
124  <p>Write an expression to match the phrase:<br...         2

[125 rows x 2 columns]